### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by TWME-TW**
Update to 1.19

### CODE REVIEW

**Comment by MenschenToaster** [comment]
Looks good. I will need to test it locally, and then it's good to go. The only thing I don't like is, that it needs to be compiled with Java 17. I would like to keep it on Java 16 for now, but then again it would most likely not compile because the Spigot API is at a higher Java Version (at least that's how Gradle behaves. I don't really know how maven does it since it has been a while since I used that)

**Comment by MenschenToaster** [comment]
Never mind, the Java Version is not an Issue since maven is set to compile for Java 8 anyway.

**Comment by TWME-TW** [comment]
（I am a Java noob

**Comment by MenschenToaster** [comment]
No problem. Everything works fine 😉

**Pull request merged**
