### PR TITLE
Add new some blocks

### PR DESCRIPTION
**Pull request by TWME-TW**
[Add new some blocks](https://github.com/MenschenToaster/CraftFlowers/issues/46)

### CODE REVIEW

**Comment by TWME-TW** [comment]
@MenschenToaster 
Do you think it's necessary to determine the placement direction based on the player's orientation?

**Comment by MenschenToaster** [comment]
> @MenschenToaster Do you think it's necessary to determine the placement direction based on the player's orientation?

For what blocks? The stems? It might be a good idea, yeah

**Comment by TWME-TW** [comment]
> > @MenschenToaster Do you think it's necessary to determine the placement direction based on the player's orientation?
> 
> For what blocks? The stems? It might be a good idea, yeah

I leave this part to you :)

**Comment by TWME-TW** [comment]
This can be merged (if there are no other problems).

**Review by MenschenToaster — APPROVED** [review]

**Pull request merged**
